"""Rename Task to Test

Revision ID: 0736a45999b8
Revises: 6782cb975f59
Create Date: 2023-04-26 22:16:49.779489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0736a45999b8'
down_revision = '6782cb975f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PRACTISE', 'EXAM', name='testtype'), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('right_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_test',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('NOT_ACTIVE', 'IN_PROGRESS', 'COMPLETED', name='activitystatus', create_type=False), nullable=True),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'test_id')
    )
    op.drop_table('user_task')
    op.drop_table('task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('task_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('type', postgresql.ENUM('TEST', 'EXAM', name='tasktype', create_type=False), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('right_answer', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='task_course_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='task_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_task',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('NOT_ACTIVE', 'IN_PROGRESS', 'COMPLETED', name='activitystatus', create_type=False), autoincrement=False, nullable=True),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='user_task_task_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_task_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'task_id', name='user_task_pkey')
    )
    op.drop_table('user_test')
    op.drop_table('test')
    # ### end Alembic commands ###
