"""add_relations

Revision ID: 7793269fb2f3
Revises: d2b34ab698ba
Create Date: 2023-04-25 20:54:02.060828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7793269fb2f3'
down_revision = 'd2b34ab698ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_course',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_ACTIVE', 'IN_PROGRESS', 'COMPLETED', name='activitystatus'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    op.create_table('user_lection',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lection_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_ACTIVE', 'IN_PROGRESS', 'COMPLETED', name='activitystatus'), nullable=True),
    sa.ForeignKeyConstraint(['lection_id'], ['lection.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'lection_id')
    )
    op.create_table('user_task',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_ACTIVE', 'IN_PROGRESS', 'COMPLETED', name='activitystatus'), nullable=True),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_task')
    op.drop_table('user_lection')
    op.drop_table('user_course')
    # ### end Alembic commands ###
