"""Make Test type not nullable

Revision ID: 7ad35e42b231
Revises: 026d5dec5a5d
Create Date: 2023-04-26 23:01:46.282695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ad35e42b231'
down_revision = '026d5dec5a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=postgresql.ENUM('PRACTISE', 'EXAM', name='testtype'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=postgresql.ENUM('PRACTISE', 'EXAM', name='testtype'),
               nullable=True)

    # ### end Alembic commands ###
